-- ## MOTORCYCLES 1',
DELETE FROM public.store_product WHERE id > 2;
INSERT INTO public.store_product(
		category_id, image, name, description, price, featured
	)
	VALUES(
'1',
'images/17A4DD7D-AD28-43B3-90ED-D7264E43E6A6.jpg',
'2022 Kawasaki Z125 PRO Base',
'All advertised vehicles and pricing are subject to dealer availability. MSRP is shown for information purposes only, this is not the dealer’s advertised or asking price. All MSRP prices exclude government fees and taxes, any finance charges, additional dealer markup (ADM), any dealer document processing charge, any electronic filing charge and any emission testing charge. See dealer for dealer’s price on vehicles displaying only MSRP. Only prices labeled “Bert’s Price” are dealer’s sale price. MSRP prices are not dealer’s prices and are shown for reference only. See dealer for dealer’s price which may include added markup. “Bert’s prices” are plus government fees and taxes, additional dealer markup (ADM), any finance charges, any dealer document processing charge, any electronic filing charge and any emission testing charge. Certain finance/rebate promotions can NOT be stacked onto the sales price of a vehicle. This can vary between brands and special promotions, please see dealer to determine if this applies to your anticipated purchase. All prices expire at close of business today. Vehicle availability is not guaranteed and is subject to change at any time. Vehicle image displayed is depicted as accurately as possible, but may be limited due to technical issues/device display quality. All information provided is believed to be accurate, but all specifications, pricing and availability must be confirmed with the dealer. Neither Bert’s Mega Mall nor Dealer Spike are responsible for any inaccuracies contained herein or use of this application.',
'3399',
true),(
'1',
'images/E2A125D5-3DF8-471B-83FC-B9291E233045.jpg',
'2022 Honda® Ruckus Base',
'All advertised vehicles and pricing are subject to dealer availability. MSRP is shown for information purposes only, this is not the dealer’s advertised or asking price. All MSRP prices exclude government fees and taxes, any finance charges, additional dealer markup (ADM), any dealer document processing charge, any electronic filing charge and any emission testing charge. See dealer for dealer’s price on vehicles displaying only MSRP. Only prices labeled “Bert’s Price” are dealer’s sale price. MSRP prices are not dealer’s prices and are shown for reference only. See dealer for dealer’s price which may include added markup. “Bert’s prices” are plus government fees and taxes, additional dealer markup (ADM), any finance charges, any dealer document processing charge, any electronic filing charge and any emission testing charge.
Certain finance/rebate promotions can NOT be stacked onto the sales price of a vehicle. This can vary between brands and special promotions, please see dealer to determine if this applies to your anticipated purchase. All prices expire at close of business today. Vehicle availability is not guaranteed and is subject to change at any time. Vehicle image displayed is depicted as accurately as possible, but may be limited due to technical issues/device display quality. All information provided is believed to be accurate, but all specifications, pricing and availability must be confirmed with the dealer. Neither Bert’s Mega Mall nor Dealer Spike are responsible for any inaccuracies contained herein or use of this application.',
'2799',
false),(
'1',
'images/262521B3-CF7B-4678-90B6-AEAE78131CD3.jpg',
'2021 Honda® Super Cub C125 ABS',
'All advertised vehicles and pricing are subject to dealer availability. MSRP is shown for information purposes only, this is not the dealer’s advertised or asking price. All MSRP prices exclude government fees and taxes, any finance charges, additional dealer markup (ADM), any dealer document processing charge, any electronic filing charge and any emission testing charge. See dealer for dealer’s price on vehicles displaying only MSRP. Only prices labeled “Bert’s Price” are dealer’s sale price. MSRP prices are not dealer’s prices and are shown for reference only. See dealer for dealer’s price which may include added markup. “Bert’s prices” are plus government fees and taxes, additional dealer markup (ADM), any finance charges, any dealer document processing charge, any electronic filing charge and any emission testing charge.
Certain finance/rebate promotions can NOT be stacked onto the sales price of a vehicle. This can vary between brands and special promotions, please see dealer to determine if this applies to your anticipated purchase. All prices expire at close of business today. Vehicle availability is not guaranteed and is subject to change at any time. Vehicle image displayed is depicted as accurately as possible, but may be limited due to technical issues/device display quality. All information provided is believed to be accurate, but all specifications, pricing and availability must be confirmed with the dealer. Neither Bert’s Mega Mall nor Dealer Spike are responsible for any inaccuracies contained herein or use of this application.',
'3749',
false),(
'1',
'images/6CBA5BFB-923A-4E79-B1B4-F4655DC1CE8E.jpg',
'2022 Kawasaki Vulcan 900 Classic',
'All advertised vehicles and pricing are subject to dealer availability. MSRP is shown for information purposes only, this is not the dealer’s advertised or asking price. All MSRP prices exclude government fees and taxes, any finance charges, additional dealer markup (ADM), any dealer document processing charge, any electronic filing charge and any emission testing charge. See dealer for dealer’s price on vehicles displaying only MSRP. Only prices labeled “Bert’s Price” are dealer’s sale price. MSRP prices are not dealer’s prices and are shown for reference only. See dealer for dealer’s price which may include added markup. “Bert’s prices” are plus government fees and taxes, additional dealer markup (ADM), any finance charges, any dealer document processing charge, any electronic filing charge and any emission testing charge.
Certain finance/rebate promotions can NOT be stacked onto the sales price of a vehicle. This can vary between brands and special promotions, please see dealer to determine if this applies to your anticipated purchase. All prices expire at close of business today. Vehicle availability is not guaranteed and is subject to change at any time. Vehicle image displayed is depicted as accurately as possible, but may be limited due to technical issues/device display quality. All information provided is believed to be accurate, but all specifications, pricing and availability must be confirmed with the dealer. Neither Bert’s Mega Mall nor Dealer Spike are responsible for any inaccuracies contained herein or use of this application.',
'8499',
false),(
-- ## ATVs 2',
'2',
'images/C9002FF7-8B86-4996-AD10-5B6E6490D8E7.jpg',
'2022 Kawasaki KFX 50',
'All advertised vehicles and pricing are subject to dealer availability. MSRP is shown for information purposes only, this is not the dealer’s advertised or asking price. All MSRP prices exclude government fees and taxes, any finance charges, additional dealer markup (ADM), any dealer document processing charge, any electronic filing charge and any emission testing charge. See dealer for dealer’s price on vehicles displaying only MSRP. Only prices labeled “Bert’s Price” are dealer’s sale price. MSRP prices are not dealer’s prices and are shown for reference only. See dealer for dealer’s price which may include added markup. “Bert’s prices” are plus government fees and taxes, additional dealer markup (ADM), any finance charges, any dealer document processing charge, any electronic filing charge and any emission testing charge.
Certain finance/rebate promotions can NOT be stacked onto the sales price of a vehicle. This can vary between brands and special promotions, please see dealer to determine if this applies to your anticipated purchase. All prices expire at close of business today. Vehicle availability is not guaranteed and is subject to change at any time. Vehicle image displayed is depicted as accurately as possible, but may be limited due to technical issues/device display quality. All information provided is believed to be accurate, but all specifications, pricing and availability must be confirmed with the dealer. Neither Bert’s Mega Mall nor Dealer Spike are responsible for any inaccuracies contained herein or use of this application.',
'2199',
true),(
'2',
'images/477F6911-C3EF-4ED3-964C-F39D8D08A272.jpg',
'2022 Can-Am® ATV OUTL MAX XTP 1000R GY CALI 22',
'All advertised vehicles and pricing are subject to dealer availability. MSRP is shown for information purposes only, this is not the dealer’s advertised or asking price. All MSRP prices exclude government fees and taxes, any finance charges, additional dealer markup (ADM), any dealer document processing charge, any electronic filing charge and any emission testing charge. See dealer for dealer’s price on vehicles displaying only MSRP. Only prices labeled “Bert’s Price” are dealer’s sale price. MSRP prices are not dealer’s prices and are shown for reference only. See dealer for dealer’s price which may include added markup. “Bert’s prices” are plus government fees and taxes, additional dealer markup (ADM), any finance charges, any dealer document processing charge, any electronic filing charge and any emission testing charge.
Certain finance/rebate promotions can NOT be stacked onto the sales price of a vehicle. This can vary between brands and special promotions, please see dealer to determine if this applies to your anticipated purchase. All prices expire at close of business today. Vehicle availability is not guaranteed and is subject to change at any time. Vehicle image displayed is depicted as accurately as possible, but may be limited due to technical issues/device display quality. All information provided is believed to be accurate, but all specifications, pricing and availability must be confirmed with the dealer. Neither Bert’s Mega Mall nor Dealer Spike are responsible for any inaccuracies contained herein or use of this application.',
'15649',
false),(
'2',
'images/4556CD52-B7F9-4970-86E9-9EEB119E9529.jpg',
'2021 Kayo FOX 70',
'Largest selection of used inventory & the world`s largest powersports dealer! For the best powersports buying experience call us today!',
'1299',
false),(
'2',
'images/B29919E7-6798-4488-BCD7-76C8F2898932.jpg',
'2021 Kayo FOX 70',
'Largest selection of used inventory & the world`s largest powersports dealer! For the best powersports buying experience call us today!',
'1299',
false),(
'2',
'images/509BA574-BE68-4365-B8F7-35E6D465A314.jpg',
'2022 Kawasaki KFX 50',
'All advertised vehicles and pricing are subject to dealer availability. MSRP is shown for information purposes only, this is not the dealer’s advertised or asking price. All MSRP prices exclude government fees and taxes, any finance charges, additional dealer markup (ADM), any dealer document processing charge, any electronic filing charge and any emission testing charge. See dealer for dealer’s price on vehicles displaying only MSRP. Only prices labeled “Bert’s Price” are dealer’s sale price. MSRP prices are not dealer’s prices and are shown for reference only. See dealer for dealer’s price which may include added markup. “Bert’s prices” are plus government fees and taxes, additional dealer markup (ADM), any finance charges, any dealer document processing charge, any electronic filing charge and any emission testing charge.
Certain finance/rebate promotions can NOT be stacked onto the sales price of a vehicle. This can vary between brands and special promotions, please see dealer to determine if this applies to your anticipated purchase. All prices expire at close of business today. Vehicle availability is not guaranteed and is subject to change at any time. Vehicle image displayed is depicted as accurately as possible, but may be limited due to technical issues/device display quality. All information provided is believed to be accurate, but all specifications, pricing and availability must be confirmed with the dealer. Neither Bert’s Mega Mall nor Dealer Spike are responsible for any inaccuracies contained herein or use of this application.',
'2199',
false),(
-- ##Jet-skis 3',
'3',
'images/952A4A50-3B2C-4B14-843A-9D91B5B1D5C0.jpg',
'2022 Kawasaki Jet Ski STX 160',
'All advertised vehicles and pricing are subject to dealer availability. MSRP is shown for information purposes only, this is not the dealer’s advertised or asking price. All MSRP prices exclude government fees and taxes, any finance charges, additional dealer markup (ADM), any dealer document processing charge, any electronic filing charge and any emission testing charge. See dealer for dealer’s price on vehicles displaying only MSRP. Only prices labeled “Bert’s Price” are dealer’s sale price. MSRP prices are not dealer’s prices and are shown for reference only. See dealer for dealer’s price which may include added markup. “Bert’s prices” are plus government fees and taxes, additional dealer markup (ADM), any finance charges, any dealer document processing charge, any electronic filing charge and any emission testing charge.',
'9899',
true),(
'3',
'images/AB581839-B447-44ED-B642-54D037F33734.jpg',
'2022 Kawasaki Jet Ski Ultra LX',
'All advertised vehicles and pricing are subject to dealer availability. MSRP is shown for information purposes only, this is not the dealer’s advertised or asking price. All MSRP prices exclude government fees and taxes, any finance charges, additional dealer markup (ADM), any dealer document processing charge, any electronic filing charge and any emission testing charge. See dealer for dealer’s price on vehicles displaying only MSRP. Only prices labeled “Bert’s Price” are dealer’s sale price. MSRP prices are not dealer’s prices and are shown for reference only. See dealer for dealer’s price which may include added markup. “Bert’s prices” are plus government fees and taxes, additional dealer markup (ADM), any finance charges, any dealer document processing charge, any electronic filing charge and any emission testing charge.
Certain finance/rebate promotions can NOT be stacked onto the sales price of a vehicle. This can vary between brands and special promotions, please see dealer to determine if this applies to your anticipated purchase. All prices expire at close of business today. Vehicle availability is not guaranteed and is subject to change at any time. Vehicle image displayed is depicted as accurately as possible, but may be limited due to technical issues/device display quality. All information provided is believed to be accurate, but all specifications, pricing and availability must be confirmed with the dealer. Neither Bert’s Mega Mall nor Dealer Spike are responsible for any inaccuracies contained herein or use of this application.',
'11699',
false),(
'3',
'images/A6F16603-7422-4CE8-827F-DF08B880451B.jpg',
'2022 Sea-Doo PW WAKE 230 IBR AUD GN 22',
'All advertised vehicles and pricing are subject to dealer availability. MSRP is shown for information purposes only, this is not the dealer’s advertised or asking price. All MSRP prices exclude government fees and taxes, any finance charges, additional dealer markup (ADM), any dealer document processing charge, any electronic filing charge and any emission testing charge. See dealer for dealer’s price on vehicles displaying only MSRP. Only prices labeled “Bert’s Price” are dealer’s sale price. MSRP prices are not dealer’s prices and are shown for reference only. See dealer for dealer’s price which may include added markup. “Bert’s prices” are plus government fees and taxes, additional dealer markup (ADM), any finance charges, any dealer document processing charge, any electronic filing charge and any emission testing charge.
Certain finance/rebate promotions can NOT be stacked onto the sales price of a vehicle. This can vary between brands and special promotions, please see dealer to determine if this applies to your anticipated purchase. All prices expire at close of business today. Vehicle availability is not guaranteed and is subject to change at any time. Vehicle image displayed is depicted as accurately as possible, but may be limited due to technical issues/device display quality. All information provided is believed to be accurate, but all specifications, pricing and availability must be confirmed with the dealer. Neither Bert’s Mega Mall nor Dealer Spike are responsible for any inaccuracies contained herein or use of this application.',
'16499',
false),(
'3',
'images/648BD50F-66CA-4763-BC11-E0869602A158.jpg',
'2022 Yamaha EX DELUXE- BLACK/MINT',
'All advertised vehicles and pricing are subject to dealer availability. MSRP is shown for information purposes only, this is not the dealer’s advertised or asking price. All MSRP prices exclude government fees and taxes, any finance charges, additional dealer markup (ADM), any dealer document processing charge, any electronic filing charge and any emission testing charge. See dealer for dealer’s price on vehicles displaying only MSRP. Only prices labeled “Bert’s Price” are dealer’s sale price. MSRP prices are not dealer’s prices and are shown for reference only. See dealer for dealer’s price which may include added markup. “Bert’s prices” are plus government fees and taxes, additional dealer markup (ADM), any finance charges, any dealer document processing charge, any electronic filing charge and any emission testing charge.
Certain finance/rebate promotions can NOT be stacked onto the sales price of a vehicle. This can vary between brands and special promotions, please see dealer to determine if this applies to your anticipated purchase. All prices expire at close of business today. Vehicle availability is not guaranteed and is subject to change at any time. Vehicle image displayed is depicted as accurately as possible, but may be limited due to technical issues/device display quality. All information provided is believed to be accurate, but all specifications, pricing and availability must be confirmed with the dealer. Neither Bert’s Mega Mall nor Dealer Spike are responsible for any inaccuracies contained herein or use of this application.',
'9299',
false),(
-- ##UTVs 4',
'4',
'images/434399CA-3C95-4472-90CE-B044DCB91ADB.jpg',
'2022 Kawasaki MULE PRO-MX',
'All advertised vehicles and pricing are subject to dealer availability. MSRP is shown for information purposes only, this is not the dealer’s advertised or asking price. All MSRP prices exclude government fees and taxes, any finance charges, additional dealer markup (ADM), any dealer document processing charge, any electronic filing charge and any emission testing charge. See dealer for dealer’s price on vehicles displaying only MSRP. Only prices labeled “Bert’s Price” are dealer’s sale price. MSRP prices are not dealer’s prices and are shown for reference only. See dealer for dealer’s price which may include added markup. “Bert’s prices” are plus government fees and taxes, additional dealer markup (ADM), any finance charges, any dealer document processing charge, any electronic filing charge and any emission testing charge.
Certain finance/rebate promotions can NOT be stacked onto the sales price of a vehicle. This can vary between brands and special promotions, please see dealer to determine if this applies to your anticipated purchase. All prices expire at close of business today. Vehicle availability is not guaranteed and is subject to change at any time. Vehicle image displayed is depicted as accurately as possible, but may be limited due to technical issues/device display quality. All information provided is believed to be accurate, but all specifications, pricing and availability must be confirmed with the dealer. Neither Bert’s Mega Mall nor Dealer Spike are responsible for any inaccuracies contained herein or use of this application.',
'10399',
true),(
'4',
'images/1252459E-4820-4BA4-8B32-0CBB6CCB7F30.jpg',
'2022 Can-Am® SSV MAV MAX XRS TURBRR TN CALI S-S',
'All advertised vehicles and pricing are subject to dealer availability. MSRP is shown for information purposes only, this is not the dealer’s advertised or asking price. All MSRP prices exclude government fees and taxes, any finance charges, additional dealer markup (ADM), any dealer document processing charge, any electronic filing charge and any emission testing charge. See dealer for dealer’s price on vehicles displaying only MSRP. Only prices labeled “Bert’s Price” are dealer’s sale price. MSRP prices are not dealer’s prices and are shown for reference only. See dealer for dealer’s price which may include added markup. “Bert’s prices” are plus government fees and taxes, additional dealer markup (ADM), any finance charges, any dealer document processing charge, any electronic filing charge and any emission testing charge.
Certain finance/rebate promotions can NOT be stacked onto the sales price of a vehicle. This can vary between brands and special promotions, please see dealer to determine if this applies to your anticipated purchase. All prices expire at close of business today. Vehicle availability is not guaranteed and is subject to change at any time. Vehicle image displayed is depicted as accurately as possible, but may be limited due to technical issues/device display quality. All information provided is believed to be accurate, but all specifications, pricing and availability must be confirmed with the dealer. Neither Bert’s Mega Mall nor Dealer Spike are responsible for any inaccuracies contained herein or use of this application.',
'37999',
false),(
'4',
'images/368FA7F9-65B7-4FE3-A9AA-C952048A7DE0.jpg',
'2021 Polaris® RZR PRO XP SPORT - WHITE LIGHTNING',
'All advertised vehicles and pricing are subject to dealer availability. MSRP is shown for information purposes only, this is not the dealer’s advertised or asking price. All MSRP prices exclude government fees and taxes, any finance charges, additional dealer markup (ADM), any dealer document processing charge, any electronic filing charge and any emission testing charge. See dealer for dealer’s price on vehicles displaying only MSRP. Only prices labeled “Bert’s Price” are dealer’s sale price. MSRP prices are not dealer’s prices and are shown for reference only. See dealer for dealer’s price which may include added markup. “Bert’s prices” are plus government fees and taxes, additional dealer markup (ADM), any finance charges, any dealer document processing charge, any electronic filing charge and any emission testing charge.
Certain finance/rebate promotions can NOT be stacked onto the sales price of a vehicle. This can vary between brands and special promotions, please see dealer to determine if this applies to your anticipated purchase. All prices expire at close of business today. Vehicle availability is not guaranteed and is subject to change at any time. Vehicle image displayed is depicted as accurately as possible, but may be limited due to technical issues/device display quality. All information provided is believed to be accurate, but all specifications, pricing and availability must be confirmed with the dealer. Neither Bert’s Mega Mall nor Dealer Spike are responsible for any inaccuracies contained herein or use of this application.',
'22999',
false),(
'4',
'images/B19818BD-3259-4196-9C19-F8D0B2AF4716.jpg',
'2021 Polaris® RZR PRO XP 4 ULT - ARMY GREEN',
'All advertised vehicles and pricing are subject to dealer availability. MSRP is shown for information purposes only, this is not the dealer’s advertised or asking price. All MSRP prices exclude government fees and taxes, any finance charges, additional dealer markup (ADM), any dealer document processing charge, any electronic filing charge and any emission testing charge. See dealer for dealer’s price on vehicles displaying only MSRP. Only prices labeled “Bert’s Price” are dealer’s sale price. MSRP prices are not dealer’s prices and are shown for reference only. See dealer for dealer’s price which may include added markup. “Bert’s prices” are plus government fees and taxes, additional dealer markup (ADM), any finance charges, any dealer document processing charge, any electronic filing charge and any emission testing charge.
Certain finance/rebate promotions can NOT be stacked onto the sales price of a vehicle. This can vary between brands and special promotions, please see dealer to determine if this applies to your anticipated purchase. All prices expire at close of business today. Vehicle availability is not guaranteed and is subject to change at any time. Vehicle image displayed is depicted as accurately as possible, but may be limited due to technical issues/device display quality. All information provided is believed to be accurate, but all specifications, pricing and availability must be confirmed with the dealer. Neither Bert’s Mega Mall nor Dealer Spike are responsible for any inaccuracies contained herein or use of this application.',
'34999',
false),(
'4',
'images/B04FB310-201C-4FDA-A8DC-4BD079AC56A6.jpg',
'2021 Yamaha YXZ1000R SS',
'All advertised vehicles and pricing are subject to dealer availability. MSRP is shown for information purposes only, this is not the dealer’s advertised or asking price. All MSRP prices exclude government fees and taxes, any finance charges, additional dealer markup (ADM), any dealer document processing charge, any electronic filing charge and any emission testing charge. See dealer for dealer’s price on vehicles displaying only MSRP. Only prices labeled “Bert’s Price” are dealer’s sale price. MSRP prices are not dealer’s prices and are shown for reference only. See dealer for dealer’s price which may include added markup. “Bert’s prices” are plus government fees and taxes, additional dealer markup (ADM), any finance charges, any dealer document processing charge, any electronic filing charge and any emission testing charge.
Certain finance/rebate promotions can NOT be stacked onto the sales price of a vehicle. This can vary between brands and special promotions, please see dealer to determine if this applies to your anticipated purchase. All prices expire at close of business today. Vehicle availability is not guaranteed and is subject to change at any time. Vehicle image displayed is depicted as accurately as possible, but may be limited due to technical issues/device display quality. All information provided is believed to be accurate, but all specifications, pricing and availability must be confirmed with the dealer. Neither Bert’s Mega Mall nor Dealer Spike are responsible for any inaccuracies contained herein or use of this application.',
'19499',
false);
